Componente de background dinâmico adicionado
Uno-Online/uno-frontend pull request #51
Opened 2023-03-28 08:14 UTC by EduNunesGithub

Criação do componente de background dinâmico.

O componente recebe por props 4 temas pré-definidos porém é possível passar um vetor de cores para criar um tema customizado.

2023-03-28 08:48 UTC, heliokroger requested changes, later dismissed

2023-03-28 08:48 UTC, heliokroger commented on src/components/common/dynamic-background/dynamic-background.module.css
> +  z-index: -1000000;
Manter `z-index` arbitrária é uma má prática. No caso de um background, ele não precisa ter `position: fixed` e ter os outros elementos por cima. Ele pode ser um container que agrupa todos os elementos do jogo dentro dele.
```html
<div class="dynamic-background">
// ...
</div>
```

2023-03-28 08:48 UTC, heliokroger commented on src/components/common/dynamic-background/dynamic-background.tsx
> +  theme?: "blue" | "green" | "red" | "yellow";
Acredito que já tenhamos constantes para cores no projeto dentro da pasta `constants`

2023-03-28 08:48 UTC, ghost commented on src/components/common/dynamic-background/dynamic-background.tsx
> +    backgroundImage: `radial-gradient(circle closest-side, #65C0E3, #3E6BD9)`,
Aqui você poderia ter criado várias classes no próprio arquivo `CSS` e as associado no objeto:
```css
.dynamic-background-blue {
  background-image: ;radial-gradient(circle closest-side, #65C0E3, #3E6BD9);
}
```
```ts
const themeClasses = { blue: styles['dynamic-background-blue'] };
```

2023-03-28 08:48 UTC, heliokroger commented on src/components/common/dynamic-background/dynamic-background.tsx
> +    backgroundImage: `radial-gradient(circle closest-side, #65C0E3, #3E6BD9)`,
* O motivo é que é sempre melhor manter todo e qualquer CSS diretamente em arquivos `.css` pelo bem da validação e formatação que o arquivo oferece no editor

2023-03-28 08:48 UTC, heliokroger commented on .yarnrc.yml
> +nodeLinker: node-modules
Arquivo sem linha nova

2023-03-28 21:54 UTC, EduNunesGithub commented
Fiz as mudanças sugeridas. Também adicionei a prop className para que seja possível customizar o componente por classes de css.

2023-04-11 11:44 UTC, guilhermeSDB approved these changes

2023-04-11 11:46 UTC, guilhermeSDB approved these changes

2023-04-11 12:04 UTC, guilhermeSDB approved these changes

2023-04-11 12:04 UTC, guilhermeSDB approved these changes

2023-04-13 12:12 UTC, merged

2023-04-13 12:13 UTC, guilhermeSDB reviewed
Muito bom